-- Auto-generado desde shared/EXAMEN DIAGNÓSTICO.xlsx
-- Hojas: PREGUNTAS + RESPUESTAS
-- Nota: en RESPUESTAS hay preguntas con 2 opciones (Verdadero/Falso) y otras con 4 opciones.

START TRANSACTION;

CREATE TABLE IF NOT EXISTS exams (
  id VARCHAR(50) PRIMARY KEY,
  section_id VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_exams_section FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE,
  INDEX idx_exams_section_id (section_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS exam_questions (
  id VARCHAR(80) PRIMARY KEY,
  exam_id VARCHAR(50) NOT NULL,
  question_number INT NOT NULL,
  question_text TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_questions_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  UNIQUE KEY uq_exam_question_number (exam_id, question_number),
  INDEX idx_exam_questions_exam_id (exam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS exam_question_options (
  id VARCHAR(90) PRIMARY KEY,
  question_id VARCHAR(80) NOT NULL,
  option_label CHAR(1) NOT NULL,
  option_text TEXT NOT NULL,
  is_correct BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_question_options_question FOREIGN KEY (question_id) REFERENCES exam_questions(id) ON DELETE CASCADE,
  UNIQUE KEY uq_question_option_label (question_id, option_label),
  INDEX idx_exam_question_options_question_id (question_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO exams (id, section_id, title, description) VALUES ('exam-sec-1-1', 'sec-1-1', 'Examen Diagnóstico', 'Preguntas y opciones importadas desde EXAMEN DIAGNÓSTICO.xlsx') ON DUPLICATE KEY UPDATE section_id=VALUES(section_id), title=VALUES(title), description=VALUES(description);

INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q001', 'exam-sec-1-1', 1, '¿Cómo se define el método de Tilt-Up?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q001-A', 'exam-sec-1-1-q001', 'A', 'Como una técnica de construcción metálica prefabricada.', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q001-B', 'exam-sec-1-1-q001', 'B', 'Como una técnica para colar elementos de concreto verticalmente.', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q001-C', 'exam-sec-1-1-q001', 'C', 'Como una técnica de ensamblaje de paneles transportados por carretera.', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q001-D', 'exam-sec-1-1-q001', 'D', 'Como una técnica para colar elementos de concreto horizontalmente en el sitio y luego inclinarlos a su posición final.', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q002', 'exam-sec-1-1', 2, '¿Cuál de las siguientes es una característica de los paneles de Tilt-Up?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q002-A', 'exam-sec-1-1-q002', 'A', 'No transfieren las cargas a la cimentación.', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q002-B', 'exam-sec-1-1-q002', 'B', 'Se construyen antes del diafragma de construcción estructural.', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q002-C', 'exam-sec-1-1-q002', 'C', 'Generalmente se manipulan múltiples veces antes de su instalación.', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q002-D', 'exam-sec-1-1-q002', 'D', 'Son de tamaño y peso que sólo permiten su construcción en el sitio.', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q003', 'exam-sec-1-1', 3, 'La____________ y__________ son ventajas del método Tilt-Up.') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q003-A', 'exam-sec-1-1-q003', 'A', 'Sustentabilidad y flexibilidad', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q003-B', 'exam-sec-1-1-q003', 'B', 'Resistencia al fuego y paisajismo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q003-C', 'exam-sec-1-1-q003', 'C', 'Sustentabilidad y paisajismo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q003-D', 'exam-sec-1-1-q003', 'D', 'Resistencia la fuego y flexibilidad', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q004', 'exam-sec-1-1', 4, 'Supera cualquier otra opción que ofrecen mampostería y madera') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q004-A', 'exam-sec-1-1-q004', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q004-B', 'exam-sec-1-1-q004', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q005', 'exam-sec-1-1', 5, 'El mayor porcentaje del uso de este método constructivo se encuentra en el sector industrial') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q005-A', 'exam-sec-1-1-q005', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q005-B', 'exam-sec-1-1-q005', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q006', 'exam-sec-1-1', 6, '¿Cual es el primer paso del proceso?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q006-A', 'exam-sec-1-1-q006', 'A', 'Colocar la cimentación', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q006-B', 'exam-sec-1-1-q006', 'B', 'Curar la losa de piso', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q006-C', 'exam-sec-1-1-q006', 'C', 'Moldear los paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q006-D', 'exam-sec-1-1-q006', 'D', 'Preparar la subrasante', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q007', 'exam-sec-1-1', 7, 'Se lleva a cabo después de colocar los paneles de muros') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q007-A', 'exam-sec-1-1-q007', 'A', 'Preparar la subrasante', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q007-B', 'exam-sec-1-1-q007', 'B', 'Moldear los paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q007-C', 'exam-sec-1-1-q007', 'C', 'Colocar la cimentación', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q007-D', 'exam-sec-1-1-q007', 'D', 'Colocar lechada debajo de los paneles', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q008', 'exam-sec-1-1', 8, '¿Que debo llevar acabo antes de retirar las riostras del muro?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q008-A', 'exam-sec-1-1-q008', 'A', 'Arriostrar los paneles de muros', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q008-B', 'exam-sec-1-1-q008', 'B', 'Colocar una franja de cierre entre los muros exteriores y la losa de piso', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q008-C', 'exam-sec-1-1-q008', 'C', 'Colar el techo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q008-D', 'exam-sec-1-1-q008', 'D', 'Limpiar las caras de los paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q009', 'exam-sec-1-1', 9, '¿Cuál es el siguiente paso después de limpiar las caras?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q009-A', 'exam-sec-1-1-q009', 'A', 'Colar columnas', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q009-B', 'exam-sec-1-1-q009', 'B', 'Aplicar tratamiento a las juntas', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q009-C', 'exam-sec-1-1-q009', 'C', 'Resanar grietas', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q009-D', 'exam-sec-1-1-q009', 'D', 'Colocar techo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q010', 'exam-sec-1-1', 10, 'El ______ forma parte de los acabados para los paneles') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q010-A', 'exam-sec-1-1-q010', 'A', 'Aserrado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q010-B', 'exam-sec-1-1-q010', 'B', 'Arriostrado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q010-C', 'exam-sec-1-1-q010', 'C', 'Curado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q010-D', 'exam-sec-1-1-q010', 'D', 'Sopleteado de arena', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q011', 'exam-sec-1-1', 11, '¿Cuantas clasificaciones básicas hay de cemento Portland?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q011-A', 'exam-sec-1-1-q011', 'A', '5', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q011-B', 'exam-sec-1-1-q011', 'B', '4', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q011-C', 'exam-sec-1-1-q011', 'C', '6', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q011-D', 'exam-sec-1-1-q011', 'D', '2', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q012', 'exam-sec-1-1', 12, '¿En que consiste el SCM que predomina en el concreto para tilt-up?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q012-A', 'exam-sec-1-1-q012', 'A', 'Puzolanas naturales, cenizas voladoras y cementos escoria', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q012-B', 'exam-sec-1-1-q012', 'B', 'Endurecimiento rápido', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q012-C', 'exam-sec-1-1-q012', 'C', 'De baja temperatura', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q012-D', 'exam-sec-1-1-q012', 'D', 'Con resistencia a los sulfatos', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q013', 'exam-sec-1-1', 13, 'El agua utilizada para las mezclas de concreto tilt-up no necesita ser potable') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q013-A', 'exam-sec-1-1-q013', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q013-B', 'exam-sec-1-1-q013', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q014', 'exam-sec-1-1', 14, 'La cantidad de aire atrapado en el concreto es mayor que el 2%') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q014-A', 'exam-sec-1-1-q014', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q014-B', 'exam-sec-1-1-q014', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q015', 'exam-sec-1-1', 15, '¿Cual es el porcentaje del volumen de concreto que conforman los agregados?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q015-A', 'exam-sec-1-1-q015', 'A', '0.7', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q015-B', 'exam-sec-1-1-q015', 'B', '0.6', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q015-C', 'exam-sec-1-1-q015', 'C', '0.8', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q015-D', 'exam-sec-1-1-q015', 'D', '0.65', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q016', 'exam-sec-1-1', 16, 'Permiten obtener la resistencia de 28 días a los 7 días') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q016-A', 'exam-sec-1-1-q016', 'A', 'Aditivo mineral', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q016-B', 'exam-sec-1-1-q016', 'B', 'Aditivos de aceleración', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q016-C', 'exam-sec-1-1-q016', 'C', 'Aditivos de aire incorporado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q016-D', 'exam-sec-1-1-q016', 'D', 'Superplastificantes', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q017', 'exam-sec-1-1', 17, 'Permiten una reducción en la dosificación del agua') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q017-A', 'exam-sec-1-1-q017', 'A', 'Superplastificantes', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q017-B', 'exam-sec-1-1-q017', 'B', 'Aditivos de aire incorporado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q017-C', 'exam-sec-1-1-q017', 'C', 'Aditivos de aceleración', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q017-D', 'exam-sec-1-1-q017', 'D', 'Aditivo mineral', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q018', 'exam-sec-1-1', 18, 'Un beneficio de usar este aditivo es una menor segregación') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q018-A', 'exam-sec-1-1-q018', 'A', 'Superplastificantes', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q018-B', 'exam-sec-1-1-q018', 'B', 'Aditivos de aire incorporado', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q018-C', 'exam-sec-1-1-q018', 'C', 'Aditivo mineral', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q018-D', 'exam-sec-1-1-q018', 'D', 'Aditivos de aceleración', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q019', 'exam-sec-1-1', 19, 'El beneficioso para reducir las presiones necesarias para el bombeo') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q019-A', 'exam-sec-1-1-q019', 'A', 'Aditivos de aceleración', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q019-B', 'exam-sec-1-1-q019', 'B', 'Aditivos de aire incorporado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q019-C', 'exam-sec-1-1-q019', 'C', 'Superplastificantes', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q019-D', 'exam-sec-1-1-q019', 'D', 'Aditivo mineral', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q020', 'exam-sec-1-1', 20, 'El revenimiento debes estar en un rango de 100 a 125 mm') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q020-A', 'exam-sec-1-1-q020', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q020-B', 'exam-sec-1-1-q020', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q021', 'exam-sec-1-1', 21, '¿Cual es la resistencia mínima especifica del concreto para losa de piso a 28 días?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q021-A', 'exam-sec-1-1-q021', 'A', '24 MPa', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q021-B', 'exam-sec-1-1-q021', 'B', '31 MPa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q021-C', 'exam-sec-1-1-q021', 'C', '20 MPa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q021-D', 'exam-sec-1-1-q021', 'D', '25 MPa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q022', 'exam-sec-1-1', 22, '¿Cual es la resistencia mínima para mezclas de cimentación?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q022-A', 'exam-sec-1-1-q022', 'A', '14 MPa', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q022-B', 'exam-sec-1-1-q022', 'B', '16 MPa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q022-C', 'exam-sec-1-1-q022', 'C', '12 MPa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q022-D', 'exam-sec-1-1-q022', 'D', '13 MPa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q023', 'exam-sec-1-1', 23, 'Tamaño máximo de agregado para la losa de piso') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q023-A', 'exam-sec-1-1-q023', 'A', '35 mm', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q023-B', 'exam-sec-1-1-q023', 'B', '38 mm', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q023-C', 'exam-sec-1-1-q023', 'C', '40 mm', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q023-D', 'exam-sec-1-1-q023', 'D', '32 mm', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q024', 'exam-sec-1-1', 24, 'Tamaño máximo de agregado para los paneles es de 25 mm') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q024-A', 'exam-sec-1-1-q024', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q024-B', 'exam-sec-1-1-q024', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q025', 'exam-sec-1-1', 25, 'Las fuerzas incurridas durante el proceso de levantamiento son a menudo más menores que las que se encuentran durante la ocupación de la construcción') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q025-A', 'exam-sec-1-1-q025', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q025-B', 'exam-sec-1-1-q025', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q026', 'exam-sec-1-1', 26, 'El refuerzo de acero se usa para soportar las fuerzas de flexión') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q026-A', 'exam-sec-1-1-q026', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q026-B', 'exam-sec-1-1-q026', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q027', 'exam-sec-1-1', 27, '¿Que tamaño de barras de refuerzo no es común en los paneles?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q027-A', 'exam-sec-1-1-q027', 'A', 'Menor que No. 5 o No. 6', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q027-B', 'exam-sec-1-1-q027', 'B', 'Mayor que No. 5 o No. 6', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q027-C', 'exam-sec-1-1-q027', 'C', 'Mayor que No. 7 o No. 8', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q027-D', 'exam-sec-1-1-q027', 'D', 'Menor que No. 7 o No. 8', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q028', 'exam-sec-1-1', 28, '¿Cuál es el área nominal de las varillas del numero 5?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q028-A', 'exam-sec-1-1-q028', 'A', '0.71 cm²', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q028-B', 'exam-sec-1-1-q028', 'B', '1.29 cm²', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q028-C', 'exam-sec-1-1-q028', 'C', '1.99 cm²', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q028-D', 'exam-sec-1-1-q028', 'D', '2.84 cm²', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q029', 'exam-sec-1-1', 29, 'La malla de refuerzo electrosoldado es un producto recomendado para uso en tilt-up') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q029-A', 'exam-sec-1-1-q029', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q029-B', 'exam-sec-1-1-q029', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q030', 'exam-sec-1-1', 30, '¿Qué peso deben soportar las silletas?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q030-A', 'exam-sec-1-1-q030', 'A', 'Del concreto', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q030-B', 'exam-sec-1-1-q030', 'B', 'De los trabajadores', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q030-C', 'exam-sec-1-1-q030', 'C', 'Del refuerzo de acero y los trabajadores durante la colocación del concreto', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q030-D', 'exam-sec-1-1-q030', 'D', 'Del acero de refuerzo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q031', 'exam-sec-1-1', 31, '¿Cuál es el material mas común para moldear las losas?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q031-A', 'exam-sec-1-1-q031', 'A', 'Acero', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q031-B', 'exam-sec-1-1-q031', 'B', 'Aluminio', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q031-C', 'exam-sec-1-1-q031', 'C', 'Madera', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q031-D', 'exam-sec-1-1-q031', 'D', 'Poliestireno', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q032', 'exam-sec-1-1', 32, '¿Que tipo de desmoldante forma jabones metálicos para la adhesión?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q032-A', 'exam-sec-1-1-q032', 'A', 'Químicamente activos', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q032-B', 'exam-sec-1-1-q032', 'B', 'Químicamente inactivos', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q032-C', 'exam-sec-1-1-q032', 'C', 'Solventes', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q032-D', 'exam-sec-1-1-q032', 'D', 'A base de cera', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q033', 'exam-sec-1-1', 33, '¿Cuál es el método de aplicación del aislamiento?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q033-A', 'exam-sec-1-1-q033', 'A', 'De bode a borde, de abajo a arriba', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q033-B', 'exam-sec-1-1-q033', 'B', 'De bode a borde, de arriba a abajo', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q033-C', 'exam-sec-1-1-q033', 'C', 'De arriba abajo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q033-D', 'exam-sec-1-1-q033', 'D', 'De bode a borde', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q034', 'exam-sec-1-1', 34, 'Grosor estándar de ladrillos para acabado') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q034-A', 'exam-sec-1-1-q034', 'A', '11 mm', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q034-B', 'exam-sec-1-1-q034', 'B', '15 mm', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q034-C', 'exam-sec-1-1-q034', 'C', '13 mm', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q034-D', 'exam-sec-1-1-q034', 'D', '12 mm', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q035', 'exam-sec-1-1', 35, 'Es un factor que afecta el curado del concreto') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q035-A', 'exam-sec-1-1-q035', 'A', 'Revenimiento', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q035-B', 'exam-sec-1-1-q035', 'B', 'Resistencia', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q035-C', 'exam-sec-1-1-q035', 'C', 'Refuerzo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q035-D', 'exam-sec-1-1-q035', 'D', 'Tiempo', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q036', 'exam-sec-1-1', 36, 'La _____ es especialmente importante en proyectos de tilt-up que tienen grandes superficies de losas sobre el terreno') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q036-A', 'exam-sec-1-1-q036', 'A', 'Tiempo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q036-B', 'exam-sec-1-1-q036', 'B', 'Temperatura', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q036-C', 'exam-sec-1-1-q036', 'C', 'Humedad', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q036-D', 'exam-sec-1-1-q036', 'D', 'Presión atmosférica', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q037', 'exam-sec-1-1', 37, 'El costal de arpilleria puede usarse cono recubrimiento para el curado') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q037-A', 'exam-sec-1-1-q037', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q037-B', 'exam-sec-1-1-q037', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q038', 'exam-sec-1-1', 38, 'El recubrimiento se dejara en su lugar de 6 a 5 días') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q038-A', 'exam-sec-1-1-q038', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q038-B', 'exam-sec-1-1-q038', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q039', 'exam-sec-1-1', 39, 'El curado predominante para áreas grandes de  concreto es rociar la superficie con un compuesto liquido.') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q039-A', 'exam-sec-1-1-q039', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q039-B', 'exam-sec-1-1-q039', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q040', 'exam-sec-1-1', 40, '¿Apartir de que temperatura deben tomarse medidas para reducir el agrietamiento en la losas?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q040-A', 'exam-sec-1-1-q040', 'A', '35 °C', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q040-B', 'exam-sec-1-1-q040', 'B', '85 °C', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q040-C', 'exam-sec-1-1-q040', 'C', '50 °C', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q040-D', 'exam-sec-1-1-q040', 'D', '29 °C', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q041', 'exam-sec-1-1', 41, 'Puede usarse una mezcla menos densa para acelerar la obtención de resistencia en tiempo frio') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q041-A', 'exam-sec-1-1-q041', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q041-B', 'exam-sec-1-1-q041', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q042', 'exam-sec-1-1', 42, 'El aditivo incorporador de aire no se añade durante la mezcla de concreto') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q042-A', 'exam-sec-1-1-q042', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q042-B', 'exam-sec-1-1-q042', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q043', 'exam-sec-1-1', 43, 'Las emisiones de bióxido de carbono en espacios cerrados afectan el curado del concreto durante las primeras 24 horas') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q043-A', 'exam-sec-1-1-q043', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q043-B', 'exam-sec-1-1-q043', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q044', 'exam-sec-1-1', 44, 'Para que el calor de los paneles apilados sea de ayuda en clima frio el tiempo de vaciado de pisos sucesivos no debe superar______') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q044-A', 'exam-sec-1-1-q044', 'A', '5 días', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q044-B', 'exam-sec-1-1-q044', 'B', '2 días', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q044-C', 'exam-sec-1-1-q044', 'C', '3 días', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q044-D', 'exam-sec-1-1-q044', 'D', '4 días', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q045', 'exam-sec-1-1', 45, '¿Cual es la temperatura mínima a la que se recomienda colar?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q045-A', 'exam-sec-1-1-q045', 'A', '-5.6 °C', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q045-B', 'exam-sec-1-1-q045', 'B', '22.3 °C', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q045-C', 'exam-sec-1-1-q045', 'C', '10.11 °C', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q045-D', 'exam-sec-1-1-q045', 'D', '6.5 °C', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q046', 'exam-sec-1-1', 46, 'Dejar cualquier molde en su lugar el mayor tiempo posible ayuda a distribuir el calor sobre superficie del concreto') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q046-A', 'exam-sec-1-1-q046', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q046-B', 'exam-sec-1-1-q046', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q047', 'exam-sec-1-1', 47, 'Es un aspecto de diseño') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q047-A', 'exam-sec-1-1-q047', 'A', 'Tipo de concreto', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q047-B', 'exam-sec-1-1-q047', 'B', 'Tamaño de panel', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q047-C', 'exam-sec-1-1-q047', 'C', 'Aditivos', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q047-D', 'exam-sec-1-1-q047', 'D', 'Tipo de refuerzo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q048', 'exam-sec-1-1', 48, 'Debe analizarse durante la etapa de preconstrucción') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q048-A', 'exam-sec-1-1-q048', 'A', 'Revenimiento', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q048-B', 'exam-sec-1-1-q048', 'B', 'Tipo de riostras', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q048-C', 'exam-sec-1-1-q048', 'C', 'Criterios que afectan la selección de la grúa', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q048-D', 'exam-sec-1-1-q048', 'D', 'Tiempo de curado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q049', 'exam-sec-1-1', 49, 'Documento que incluye la ubicación de los insertos') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q049-A', 'exam-sec-1-1-q049', 'A', 'Detallado de paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q049-B', 'exam-sec-1-1-q049', 'B', 'Planos de taller', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q049-C', 'exam-sec-1-1-q049', 'C', 'Planos de paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q049-D', 'exam-sec-1-1-q049', 'D', 'Manual de montaje', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q050', 'exam-sec-1-1', 50, 'Documento que incluye las dimensiones del panel') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q050-A', 'exam-sec-1-1-q050', 'A', 'Detallado de paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q050-B', 'exam-sec-1-1-q050', 'B', 'Planos de taller', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q050-C', 'exam-sec-1-1-q050', 'C', 'Planos de paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q050-D', 'exam-sec-1-1-q050', 'D', 'Manual de montaje', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q051', 'exam-sec-1-1', 51, 'El espesor del panel y su refuerzo de acero proporcionan una resistencia a las siguientes fuerzas') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q051-A', 'exam-sec-1-1-q051', 'A', 'De torsión', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q051-B', 'exam-sec-1-1-q051', 'B', 'De compresión', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q051-C', 'exam-sec-1-1-q051', 'C', 'Paralelas al plano, verticales y laterales', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q051-D', 'exam-sec-1-1-q051', 'D', 'Horizontales', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q052', 'exam-sec-1-1', 52, 'Es la altura sin soporte') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q052-A', 'exam-sec-1-1-q052', 'A', 'Razón H/T', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q052-B', 'exam-sec-1-1-q052', 'B', 'Razón S/T', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q052-C', 'exam-sec-1-1-q052', 'C', 'Razón H/S', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q052-D', 'exam-sec-1-1-q052', 'D', 'Razón R/S', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q053', 'exam-sec-1-1', 53, 'Las moldaduras no reducen el espesor estructural') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q053-A', 'exam-sec-1-1-q053', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q053-B', 'exam-sec-1-1-q053', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q054', 'exam-sec-1-1', 54, '¿Que significa modular el edificio?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q054-A', 'exam-sec-1-1-q054', 'A', 'Determinar como se colocara la cimbra', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q054-B', 'exam-sec-1-1-q054', 'B', 'Determinar como se colaran los paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q054-C', 'exam-sec-1-1-q054', 'C', 'Determinar como se dividirán los muros en paneles', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q054-D', 'exam-sec-1-1-q054', 'D', 'Determinar como se colocaran los paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q055', 'exam-sec-1-1', 55, '¿Cual es la longitud que debe evitarse en paneles de dintel?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q055-A', 'exam-sec-1-1-q055', 'A', '11.5 m', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q055-B', 'exam-sec-1-1-q055', 'B', '13.5 m', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q055-C', 'exam-sec-1-1-q055', 'C', '15 m', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q055-D', 'exam-sec-1-1-q055', 'D', '12.2 m', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q056', 'exam-sec-1-1', 56, '¿Cual es la longitud minia que debe tener un panel solido entre aberturas o abertura y borde de un panel?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q056-A', 'exam-sec-1-1-q056', 'A', '1.5 m', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q056-B', 'exam-sec-1-1-q056', 'B', '0.45 m', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q056-C', 'exam-sec-1-1-q056', 'C', '0.5 m', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q056-D', 'exam-sec-1-1-q056', 'D', '1.85 m', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q057', 'exam-sec-1-1', 57, 'Es un factor que influye en el tamaño de un panel') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q057-A', 'exam-sec-1-1-q057', 'A', 'La capacidad de la grúa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q057-B', 'exam-sec-1-1-q057', 'B', 'Su peso', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q057-C', 'exam-sec-1-1-q057', 'C', 'El presupuesto', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q057-D', 'exam-sec-1-1-q057', 'D', 'Todas las anteriores', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q058', 'exam-sec-1-1', 58, 'El tamaño de un panel afecta el tiempo de levantamiento') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q058-A', 'exam-sec-1-1-q058', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q058-B', 'exam-sec-1-1-q058', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q059', 'exam-sec-1-1', 59, '¿Que determina un panel fuera de plano?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q059-A', 'exam-sec-1-1-q059', 'A', 'Que se cole en el plano horizontal', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q059-B', 'exam-sec-1-1-q059', 'B', 'Que no este en los planos de taller', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q059-C', 'exam-sec-1-1-q059', 'C', 'Que su refuerzo sea de malla', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q059-D', 'exam-sec-1-1-q059', 'D', 'Que se desvié de una figura rectilínea', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q060', 'exam-sec-1-1', 60, 'Los paneles curvos son mas costos') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q060-A', 'exam-sec-1-1-q060', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q060-B', 'exam-sec-1-1-q060', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q061', 'exam-sec-1-1', 61, '¿En que consiste el proceso de secuencia y disposición de paneles?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q061-A', 'exam-sec-1-1-q061', 'A', 'Acceso al sitio y circulación de la grúa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q061-B', 'exam-sec-1-1-q061', 'B', 'Tamaños y pesos de paneles', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q061-C', 'exam-sec-1-1-q061', 'C', 'Tipos y capacidades de las grúas disponibles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q061-D', 'exam-sec-1-1-q061', 'D', 'Muestra donde se cimbrarán, su posición final  y sus secuencias de colado y montaje.', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q062', 'exam-sec-1-1', 62, 'Generalmente, se necesita cuando menos el _________ del área del piso para los camiones de concreto y para maniobrar la grúa durante el levantamiento') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q062-A', 'exam-sec-1-1-q062', 'A', '0.2', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q062-B', 'exam-sec-1-1-q062', 'B', '0.4', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q062-C', 'exam-sec-1-1-q062', 'C', '0.5', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q062-D', 'exam-sec-1-1-q062', 'D', '0.35', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q063', 'exam-sec-1-1', 63, 'Es un factor que afecta el espacio de la losa de piso utilizable') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q063-A', 'exam-sec-1-1-q063', 'A', 'El peso de los paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q063-B', 'exam-sec-1-1-q063', 'B', 'La maniobrabilidad', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q063-C', 'exam-sec-1-1-q063', 'C', 'La franja de cierre', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q063-D', 'exam-sec-1-1-q063', 'D', 'El tipo de suelo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q064', 'exam-sec-1-1', 64, 'Tipo de grúa usada para montar los paneles') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q064-A', 'exam-sec-1-1-q064', 'A', 'Pluma de celosía montada en camión', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q064-B', 'exam-sec-1-1-q064', 'B', 'Pluma de celosía montada en rieles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q064-C', 'exam-sec-1-1-q064', 'C', 'Pluma hidráulica', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q064-D', 'exam-sec-1-1-q064', 'D', 'Todas las anteriores', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q065', 'exam-sec-1-1', 65, '¿De que depende si el panel se levanta desde el interior o exterior?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q065-A', 'exam-sec-1-1-q065', 'A', 'Tipo y capacidad de la grúa', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q065-B', 'exam-sec-1-1-q065', 'B', 'Potencial de dañar la losa de piso', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q065-C', 'exam-sec-1-1-q065', 'C', 'Accesibilidad', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q065-D', 'exam-sec-1-1-q065', 'D', 'Todas las anteriores', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q066', 'exam-sec-1-1', 66, 'Es un requisito para seleccionar la grúa') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q066-A', 'exam-sec-1-1-q066', 'A', 'Distancia que la grúa transporta al panel', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q066-B', 'exam-sec-1-1-q066', 'B', 'El tipo de suelo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q066-C', 'exam-sec-1-1-q066', 'C', 'El numero de paneles que se colocara', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q066-D', 'exam-sec-1-1-q066', 'D', 'El acabado de los paneles', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q067', 'exam-sec-1-1', 67, 'Cuando se recogen paneles grandes, es poco común emplear el uso de una grúa oruga.') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q067-A', 'exam-sec-1-1-q067', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q067-B', 'exam-sec-1-1-q067', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q068', 'exam-sec-1-1', 68, 'Debe estimarse que la grúa sea 2 a 3 veces el tamaño del panel más pesado') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q068-A', 'exam-sec-1-1-q068', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q068-B', 'exam-sec-1-1-q068', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q069', 'exam-sec-1-1', 69, 'El _______ es un acabo que se usa con frecuencia') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q069-A', 'exam-sec-1-1-q069', 'A', 'Pulido', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q069-B', 'exam-sec-1-1-q069', 'B', 'Raspado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q069-C', 'exam-sec-1-1-q069', 'C', 'Agregado expuesto', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q069-D', 'exam-sec-1-1-q069', 'D', 'Moldeado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q070', 'exam-sec-1-1', 70, '¿Que requisitos determinan la resistencia de los paneles a incendios?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q070-A', 'exam-sec-1-1-q070', 'A', 'Insertos', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q070-B', 'exam-sec-1-1-q070', 'B', 'Curado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q070-C', 'exam-sec-1-1-q070', 'C', 'Recubrimiento', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q070-D', 'exam-sec-1-1-q070', 'D', 'Acabado', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q071', 'exam-sec-1-1', 71, '¿A que se refiere el factor R?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q071-A', 'exam-sec-1-1-q071', 'A', 'Desempeño térmico de los paneles de muro', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q071-B', 'exam-sec-1-1-q071', 'B', 'La altura sin soporte', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q071-C', 'exam-sec-1-1-q071', 'C', 'El revenimiento', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q071-D', 'exam-sec-1-1-q071', 'D', 'La resistencia contra incendios', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q072', 'exam-sec-1-1', 72, '¿En que se basa el espesor requerido del panel en cuanto a desempeño termino?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q072-A', 'exam-sec-1-1-q072', 'A', 'NTC 111', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q072-B', 'exam-sec-1-1-q072', 'B', 'ASTM C270', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q072-C', 'exam-sec-1-1-q072', 'C', 'ACI 318', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q072-D', 'exam-sec-1-1-q072', 'D', 'IECC', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q073', 'exam-sec-1-1', 73, 'Los edificios con un alto contenido de humedad o que tienen el potencial de mal uso no pueden ser buenos candidatos para sistemas aplicados en interiores.') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q073-A', 'exam-sec-1-1-q073', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q073-B', 'exam-sec-1-1-q073', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q074', 'exam-sec-1-1', 74, 'Los sistemas en interiores también aíslan el concreto en el lado frío del muro') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q074-A', 'exam-sec-1-1-q074', 'A', 'VERDADERO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q074-B', 'exam-sec-1-1-q074', 'B', 'FALSO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q075', 'exam-sec-1-1', 75, 'Se posicionan contra la cara boca abajo son predominantemente EPS por naturaleza.') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q075-A', 'exam-sec-1-1-q075', 'A', 'Sistemas de aislamiento Steelfoam Techo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q075-B', 'exam-sec-1-1-q075', 'B', 'Sistemas de aislamiento Concreto aislante ligero', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q075-C', 'exam-sec-1-1-q075', 'C', 'Sistemas de aislamiento con poliuretano', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q075-D', 'exam-sec-1-1-q075', 'D', 'Sistemas de aislamiento integralmente colados.', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q076', 'exam-sec-1-1', 76, '¿En que consisten los paneles emparedados?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q076-A', 'exam-sec-1-1-q076', 'A', 'En dos capas de concreto separadas por una capa de aislamiento rígido', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q076-B', 'exam-sec-1-1-q076', 'B', 'En dos capas de concreto separadas por una capa de refuerzo de acero', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q076-C', 'exam-sec-1-1-q076', 'C', 'En dos capas de concreto separadas por una capa madera', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q076-D', 'exam-sec-1-1-q076', 'D', 'En dos capas de concreto separadas por una capa de tabla roca', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q077', 'exam-sec-1-1', 77, '¿Cual es el aislamiento predilecto en paneles emparedados?') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q077-A', 'exam-sec-1-1-q077', 'A', 'Vinilo', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q077-B', 'exam-sec-1-1-q077', 'B', 'Madera aligerada', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q077-C', 'exam-sec-1-1-q077', 'C', 'Poliisocianurato', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q077-D', 'exam-sec-1-1-q077', 'D', 'Poliestireno', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q078', 'exam-sec-1-1', 78, 'Usan conectores rígidos para crear un panel') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q078-A', 'exam-sec-1-1-q078', 'A', 'Paneles compuestos', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q078-B', 'exam-sec-1-1-q078', 'B', 'Paneles parcialmente compuestos', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q078-C', 'exam-sec-1-1-q078', 'C', 'Muros de media asta', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q078-D', 'exam-sec-1-1-q078', 'D', 'Muros repaldados', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_questions (id, exam_id, question_number, question_text) VALUES ('exam-sec-1-1-q079', 'exam-sec-1-1', 79, 'La vibración o presión sobre el tablero de aislamiento no asegura que el concreto fluya alrededor de cualquier deformación o desplazamiento en el conector.') ON DUPLICATE KEY UPDATE question_text=VALUES(question_text);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q079-A', 'exam-sec-1-1-q079', 'A', 'VERDADERO', 0) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);
INSERT INTO exam_question_options (id, question_id, option_label, option_text, is_correct) VALUES ('exam-sec-1-1-q079-B', 'exam-sec-1-1-q079', 'B', 'FALSO', 1) ON DUPLICATE KEY UPDATE option_text=VALUES(option_text), is_correct=VALUES(is_correct);

COMMIT;
